### ISSUE TITLE
Crash with shooting a Snake  from Alex Mobs

### ISSUE THREAD

**Issue by talhanation** [baguchan/PierceArrow#1]
crash with Alex-Mobs 

I shot a snake with a bow.

PierceArrow-1.16.5-1.0.0

Here is the Crash Log: hope you can fix it.
https://crashy.net/oTivP4siFSvT8w74fcuL

best regards talhanation.

**Comment by baguchi** [comment]
1.16.5 version is very buggy, If possible you should changed to 1.17.1+ version
