### ISSUE TITLE
Please fix the 1.16.5 crash

### ISSUE THREAD

**Issue by ekiplier** [baguchan/PierceArrow#3]
I really like the idea of this mod but I want to include it in a 1.16.5 modpack and I can't because it crashes the game when hitting certain modded entities

**Comment by hivjSiricnak** [comment]
I think we should make a list from wich mods brakes the game when the creatures got hit by an arrow or bee. For now I would like to start this list with the Ice and Fire. I noticed it when a mob from it attacked a bee and crashed the game. I will inform the creator of Ice and Fire and ask him to pick up the line with the creator of this mod. It would looking good to see a dragon filled with arrows 😃.

**Comment by baguchi** [comment]
fixed in 1.16.5-1.1.0!
