### ISSUE TITLE
Blazes,Villagers,Illagers are not affecting to arrow

### ISSUE THREAD

**Issue by RashidZainal2** [baguchan/PierceArrow#5]
Hey Bagu Chan i wanna know that Villagers Blazes & Illagers are not affecting to the arrow pls watch the video im using 1.17.1

video link : https://www.youtube.com/watch?v=mTEvKyuajgk

**Comment by baguchi** [comment]
in the piercearrow-1.19.2-2.0.0 more mobs can attach arrow!
